TDI specific bazel changes
ffoulkes/ipdk.stratum pull request #2
Opened 2022-09-17 19:00 UTC by ravi861

Signed-off-by: Ravi Vantipalli <ravi.vantipalli@intel.com>

2022-09-17 19:03 UTC, ravi861 commented
This commit adds the relevant TDI related bazel files.
bazel/external/tofino.BUILD
stratum/hal/lib/tdi/tdi.bzl

In addition all references to compile time macros related to SDE_9_* are removed.

2022-09-17 19:06 UTC, ravi861 commented on stratum/hal/lib/tdi/tdi.bzl
> +    # this would be a good place figure the target. Tofino for now.
I named this tdi.bzl since this file is required for all targets. We will need to perform some bazel magic here to correctly pick tofino/dpdk/mev here.

2022-09-17 21:22 UTC, ffoulkes requested changes

2022-09-17 21:22 UTC, ffoulkes commented on stratum/hal/lib/tdi/tdi_sde_wrapper.cc
>  std::string TdiSdeWrapper::GetSdeVersion() const {
This will do for now, but we really need to get away from having Stratum jump through hoops to obtain a string representation of the SDE version number. It's an unmaintainable kludge.

The SDE should have an API that returns a string representation of its version number.

2022-09-17 21:22 UTC, ffoulkes commented on stratum/hal/lib/tdi/tdi.bzl
> +# SPDX-License-Identifier: Apache-2.0
Also: `Copyright 2022 Intel Corporation`

2022-09-17 21:22 UTC, ffoulkes commented on stratum/hal/lib/tdi/tdi.bzl
> +        print("SDE_INSTALL is deprecated, please use SDE_INSTALL_TAR")
I don't see why we need to deprecate `SDE_INSTALL` in favor of `SDE_INSTALL_TAR`.

Please delete this `print` statement.

2022-09-18 18:04 UTC, ravi861 commented on stratum/hal/lib/tdi/tdi.bzl
> +    # this would be a good place figure the target. Tofino for now.
We can start with tofino.bzl but I would rather not have different versions of this file since the functionality would likely be the same in each file. Changed for now.

2022-09-18 18:04 UTC, ravi861 commented on WORKSPACE
> +load("//stratum/hal/lib/tdi:tdi.bzl", "tdi_configure")
Done

2022-09-19 16:07 UTC, ffoulkes approved these changes
LGTM

Signed-off-by: Derek Foster derek.foster@intel.com

2022-09-19 16:13 UTC, ffoulkes commented
Signed-off-by: Derek Foster derek.foster@intel.com

2022-09-19 16:15 UTC, merged